services:
  - type: web
    name: backend-flask
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --listen=0.0.0.0:$PORT app:app
    autoDeploy: true
    repo: https://github.com/Vishal-V-D/Backend_flask.git
    branch: main
